# Generated by Django 5.0.7 on 2025-01-01 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.IntegerField()),
                ('vigente', models.BooleanField(default=True)),
                ('qr_codigo', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('id_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='myapp.sector')),
            ],
        ),
    ]
