# Generated by Django 5.0.7 on 2025-01-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(default='', max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('vigente', models.BooleanField(default=False)),
            ],
        ),
    ]
