# Generated by Django 5.0.7 on 2025-03-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesas',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
