# Generated by Django 5.0.7 on 2025-03-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mesas_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
    ]
