# Generated by Django 5.0.7 on 2025-02-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_detallepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad_item',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(auto_now_add=True),
        ),
    ]
