# Generated by Django 5.0.7 on 2025-03-07 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_articulos_stock_perfilusuario_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='articulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='myapp.articulos', verbose_name='Artículo'),
        ),
    ]
