# Generated by Django 5.0.7 on 2025-03-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_stock_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cobrado', 'Cobrado')], default='pendiente', max_length=20),
        ),
    ]
